<a href="https://colab.research.google.com/github/dlscks/pythondemo/blob/main/python_12_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 3차원 이상에서 차원 구분법

In [1]:
import numpy as np

In [3]:
# 0부터 24미만 까지 생성
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [4]:
# print하면 array라는 글자는 안보인다.
# 공백은 그대로 보인다. -> 차원 구분 가능
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [5]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
b[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
b[0,1]

array([4, 5, 6, 7])

In [9]:
b[1,1]

array([16, 17, 18, 19])

In [10]:
b[0,1,3]

7

### fancy indexing와 indexing 차이
- indexing은 원래 차원에서 하나 감소해서 가져오고 fancy indexing은 원래 차원 그대로 가져온다.

In [11]:
# indexing은 차원이 하나 감소해서 가져온다.(3차원 2차원으로 가져온다.)
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
# fancy indexing은 원래 3차원 그대로 가져온다.
b[[0]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [14]:
# b[0]은 b[0,:,:]의 단푹 표현이다.
b[[0],:,:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [16]:
# b의 0번째,공간,1번째 행 미만, 열전체
b[0, :1, :]

array([[0, 1, 2, 3]])

### Ellipsis
...(Ellipsis)은 이후로 모든 것을 의미한다.

In [17]:
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
type(...)

ellipsis

In [22]:
b[0] # 생략기법
b[0,:,:] # slicing 기법
b[0,...] # Ellipsis기법

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
# 숫자 1,5,9만 가져온다
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [27]:
b[0,:,1]

array([1, 5, 9])

In [29]:
b[0,[0,1,2],:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
# 숫자 1,5,9,3,7,11가져오기
b[0,:,[1,3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])