<a href="https://colab.research.google.com/github/dlscks/pythondemo/blob/main/python_23_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

### 버전 확인

In [3]:
# python
import sys
print(sys.version)

!python --version

3.8.16 (default, Dec  7 2022, 01:12:13) 
[GCC 7.5.0]
Python 3.8.16


In [4]:
#numpy
np.__version__

'1.21.6'

In [5]:
#pandas
pd.__version__

'1.3.5'

In [ ]:
# 구글 colab
!pip freeze

- numpy datatype : ndarry, matrix
- pandas datatype : Series(벡터), DataFrame(행렬)

In [7]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/python_demo

Mounted at /content/drive
/content/drive/MyDrive/python_demo


### 파일 형식 데이터 불러오기

In [8]:
# 읽어오는 파일에 컬럼명이 없으면 header=None을 설정한다.
# 그렇지 않으면 첫번째 줄을 컬럼명으로 인식을 하기 때문이다.
# header 파라미터의 default:'infer'
data = pd.read_csv('pdsample/num.txt', header=None)
data

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [9]:
type(data)

pandas.core.frame.DataFrame

In [20]:
# 컬럼(열)
print(data[0])
print(type(data[0])) # Series

<class 'pandas.core.series.Series'>


In [19]:
# index(행)
print(data.iloc[0])
print(type(data.iloc[0])) # Series

0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>


In [13]:
# numpy 참고
a = np.arange(12).reshape(3,4)
print(a)
print(a[1][2])
print(a[1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[4 5 6 7]


In [21]:
# python list 참고
b = [[ 0 , 1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11]]
print(b[1][2])
print(b[1])
#print(b[1,2:]) # list에서는 슬라이싱 안됨

6
[4, 5, 6, 7]


In [23]:
# .values 하면 numpy 포맷으로 변환한다.
# 내부적으로 numpy로 되어 있기 때문에 가능하다.
print(data.values)
print(type(data.values))
data.values

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# __array__가 있으면 numpy와 호환된다.
dir(data)

### 웹 주소에서 데이터 불러오기

In [26]:
# header은 기본이 첫줄을 컬럼명으로 가져오도록 설정이 되어 있기 때문에 header='infer'생략 가능하다.
data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv', header='infer')
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [27]:
# 전반적인 데이터 정보 확인
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [29]:
# 기본적으로 앞의 5개를 보여준다.
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [31]:
# head와 반대로 마지막 5개를 보여준다.
data.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [32]:
# random()으로 1개씩 보여준다.
data.sample()

total_bill   tip   sex smoker  day    time  size
211       25.89  5.16  Male    Yes  Sat  Dinner     4

In [37]:
# 보여줄 갯수를 지정할 수 있음
#data.head(10)
#data.tail(10)
data.sample(10)

total_bill   tip     sex smoker   day    time  size
199       13.51  2.00    Male    Yes  Thur   Lunch     2
52        34.81  5.20  Female     No   Sun  Dinner     4
44        30.40  5.60    Male     No   Sun  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
96        27.28  4.00    Male    Yes   Fri  Dinner     2
68        20.23  2.01    Male     No   Sat  Dinner     2
136       10.33  2.00  Female     No  Thur   Lunch     2
128       11.38  2.00  Female     No  Thur   Lunch     2
49        18.04  3.00    Male     No   Sun  Dinner     2
0         16.99  1.01  Female     No   Sun  Dinner     2

In [39]:
data.values

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [40]:
data.index

RangeIndex(start=0, stop=244, step=1)

In [41]:
data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')